#include <cppunit\extensions\HelperMacros.h>
#include "agn934xni.h"
using namespace CppUnit;	

//#pragma comment (lib,"agn934xni.lib")
//#pragma comment (lib,"ivi.lib")
//#pragma comment (lib,"cppunitd_dll.lib")

class DriverNormalFunctionalityTest : public TestFixture
{
	CPPUNIT_TEST_SUITE( DriverNormalFunctionalityTest);		
	
    /***** Begin of IviSpecAnBase Group Testing *****/

	CPPUNIT_TEST(testAGN934XNI_ATTR_ACTIVE_TRACE_defaultValue_ReadWrite_NullChannel_Index0);

	CPPUNIT_TEST(testAGN934XNI_ATTR_TRACE_MATH_TYPE_defaultValue_ReadWrite_NullChannel_Index0);
	CPPUNIT_TEST(testAGN934XNI_ATTR_TRACE_MATH_TYPE_DiscreteValue_ReadWrite_NullChannel_Index1);
	CPPUNIT_TEST(testAGN934XNI_ATTR_TRACE_MATH_TYPE_DiscreteValue_ReadWrite_NullChannel_Index2);

	CPPUNIT_TEST(testAGN934XNI_ATTR_HIGH_SENSITIVITY_ENABLE_defaultValue_ReadWrite_NullChannel_Index0);

	CPPUNIT_TEST(testAGN934XNI_ATTR_VBW_RBW_RATIO_AUTO_defaultValue_ReadWrite_NullChannel_Index0);

	CPPUNIT_TEST(testAGN934XNI_ATTR_VBW_RBW_RATIO_defaultValue_ReadWrite_NullChannel_Index0);
//	CPPUNIT_TEST(testAGN934XNI_ATTR_VBW_RBW_RATIO_CloseminimumValue_ReadWrite_NullChannel_Index1);
//	CPPUNIT_TEST(testAGN934XNI_ATTR_VBW_RBW_RATIO_ClosemaximumValue_ReadWrite_NullChannel_Index1);
//	CPPUNIT_TEST(testAGN934XNI_ATTR_VBW_RBW_RATIO_RandomValue_ReadWrite_NullChannel_Index1);
	CPPUNIT_TEST(testAGN934XNI_ATTR_VBW_RBW_RATIO_ViolationMinValue_ReadWrite_NullChannel_Index1);
	CPPUNIT_TEST(testAGN934XNI_ATTR_VBW_RBW_RATIO_ViolationMaxValue_ReadWrite_NullChannel_Index1);

	CPPUNIT_TEST(testAGN934XNI_ATTR_AVERAGE_DURATION_ENABLE_defaultValue_ReadWrite_REP_1_Index0);

	CPPUNIT_TEST(testAGN934XNI_ATTR_AVERAGE_DURATION_ENABLE_defaultValue_ReadWrite_REP_2_Index0);

	CPPUNIT_TEST(testAGN934XNI_ATTR_AVERAGE_DURATION_ENABLE_defaultValue_ReadWrite_REP_3_Index0);

	CPPUNIT_TEST(testAGN934XNI_ATTR_AVERAGE_DURATION_ENABLE_defaultValue_ReadWrite_REP_4_Index0);

	CPPUNIT_TEST(testAGN934XNI_ATTR_AVERAGE_DURATION_defaultValue_ReadWrite_REP_1_Index0);

	CPPUNIT_TEST(testAGN934XNI_ATTR_AVERAGE_DURATION_defaultValue_ReadWrite_REP_2_Index0);

	CPPUNIT_TEST(testAGN934XNI_ATTR_AVERAGE_DURATION_defaultValue_ReadWrite_REP_3_Index0);

	CPPUNIT_TEST(testAGN934XNI_ATTR_AVERAGE_DURATION_defaultValue_ReadWrite_REP_4_Index0);

	CPPUNIT_TEST(testAGN934XNI_ATTR_AVERAGE_TYPE_defaultValue_ReadWrite_NullChannel_Index0);
	CPPUNIT_TEST(testAGN934XNI_ATTR_AVERAGE_TYPE_DiscreteValue_ReadWrite_NullChannel_Index1);
	CPPUNIT_TEST(testAGN934XNI_ATTR_AVERAGE_TYPE_DiscreteValue_ReadWrite_NullChannel_Index2);
	CPPUNIT_TEST(testAGN934XNI_ATTR_AVERAGE_TYPE_DiscreteValue_ReadWrite_NullChannel_Index3);

	CPPUNIT_TEST(testAGN934XNI_ATTR_AVERAGE_ENABLE_defaultValue_ReadWrite_REP_1_Index0);

	CPPUNIT_TEST(testAGN934XNI_ATTR_AVERAGE_ENABLE_defaultValue_ReadWrite_REP_2_Index0);

	CPPUNIT_TEST(testAGN934XNI_ATTR_AVERAGE_ENABLE_defaultValue_ReadWrite_REP_3_Index0);

	CPPUNIT_TEST(testAGN934XNI_ATTR_AVERAGE_ENABLE_defaultValue_ReadWrite_REP_4_Index0);

	CPPUNIT_TEST(testAGN934XNI_ATTR_AVERAGE_COUNT_defaultValue_ReadWrite_REP_1_Index0);
	CPPUNIT_TEST(testAGN934XNI_ATTR_AVERAGE_COUNT_CloseminimumValue_ReadWrite_REP_1_Index1);
	CPPUNIT_TEST(testAGN934XNI_ATTR_AVERAGE_COUNT_ClosemaximumValue_ReadWrite_REP_1_Index1);
	CPPUNIT_TEST(testAGN934XNI_ATTR_AVERAGE_COUNT_RandomValue_ReadWrite_REP_1_Index1);
	CPPUNIT_TEST(testAGN934XNI_ATTR_AVERAGE_COUNT_ViolationMinValue_ReadWrite_REP_1_Index1);
	CPPUNIT_TEST(testAGN934XNI_ATTR_AVERAGE_COUNT_ViolationMaxValue_ReadWrite_REP_1_Index1);

	CPPUNIT_TEST(testAGN934XNI_ATTR_AVERAGE_COUNT_defaultValue_ReadWrite_REP_2_Index0);
	CPPUNIT_TEST(testAGN934XNI_ATTR_AVERAGE_COUNT_CloseminimumValue_ReadWrite_REP_2_Index1);
	CPPUNIT_TEST(testAGN934XNI_ATTR_AVERAGE_COUNT_ClosemaximumValue_ReadWrite_REP_2_Index1);
	CPPUNIT_TEST(testAGN934XNI_ATTR_AVERAGE_COUNT_RandomValue_ReadWrite_REP_2_Index1);
	CPPUNIT_TEST(testAGN934XNI_ATTR_AVERAGE_COUNT_ViolationMinValue_ReadWrite_REP_2_Index1);
	CPPUNIT_TEST(testAGN934XNI_ATTR_AVERAGE_COUNT_ViolationMaxValue_ReadWrite_REP_2_Index1);

	CPPUNIT_TEST(testAGN934XNI_ATTR_AVERAGE_COUNT_defaultValue_ReadWrite_REP_3_Index0);
	CPPUNIT_TEST(testAGN934XNI_ATTR_AVERAGE_COUNT_CloseminimumValue_ReadWrite_REP_3_Index1);
	CPPUNIT_TEST(testAGN934XNI_ATTR_AVERAGE_COUNT_ClosemaximumValue_ReadWrite_REP_3_Index1);
	CPPUNIT_TEST(testAGN934XNI_ATTR_AVERAGE_COUNT_RandomValue_ReadWrite_REP_3_Index1);
	CPPUNIT_TEST(testAGN934XNI_ATTR_AVERAGE_COUNT_ViolationMinValue_ReadWrite_REP_3_Index1);
	CPPUNIT_TEST(testAGN934XNI_ATTR_AVERAGE_COUNT_ViolationMaxValue_ReadWrite_REP_3_Index1);

	CPPUNIT_TEST(testAGN934XNI_ATTR_AVERAGE_COUNT_defaultValue_ReadWrite_REP_4_Index0);
	CPPUNIT_TEST(testAGN934XNI_ATTR_AVERAGE_COUNT_CloseminimumValue_ReadWrite_REP_4_Index1);
	CPPUNIT_TEST(testAGN934XNI_ATTR_AVERAGE_COUNT_ClosemaximumValue_ReadWrite_REP_4_Index1);
	CPPUNIT_TEST(testAGN934XNI_ATTR_AVERAGE_COUNT_RandomValue_ReadWrite_REP_4_Index1);
	CPPUNIT_TEST(testAGN934XNI_ATTR_AVERAGE_COUNT_ViolationMinValue_ReadWrite_REP_4_Index1);
	CPPUNIT_TEST(testAGN934XNI_ATTR_AVERAGE_COUNT_ViolationMaxValue_ReadWrite_REP_4_Index1);

	CPPUNIT_TEST(testAGN934XNI_ATTR_MEASUREMENT_TYPE_defaultValue_ReadWrite_NullChannel_Index0);
	CPPUNIT_TEST(testAGN934XNI_ATTR_MEASUREMENT_TYPE_DiscreteValue_ReadWrite_NullChannel_Index1);
	CPPUNIT_TEST(testAGN934XNI_ATTR_MEASUREMENT_TYPE_DiscreteValue_ReadWrite_NullChannel_Index2);
	CPPUNIT_TEST(testAGN934XNI_ATTR_MEASUREMENT_TYPE_DiscreteValue_ReadWrite_NullChannel_Index3);
	CPPUNIT_TEST(testAGN934XNI_ATTR_MEASUREMENT_TYPE_DiscreteValue_ReadWrite_NullChannel_Index4);
	CPPUNIT_TEST(testAGN934XNI_ATTR_MEASUREMENT_TYPE_DiscreteValue_ReadWrite_NullChannel_Index5);

	CPPUNIT_TEST(testAGN934XNI_ATTR_INSTRUMENT_MODE_defaultValue_ReadWrite_NullChannel_Index0);
	CPPUNIT_TEST(testAGN934XNI_ATTR_INSTRUMENT_MODE_DiscreteValue_ReadWrite_NullChannel_Index1);
	CPPUNIT_TEST(testAGN934XNI_ATTR_INSTRUMENT_MODE_DiscreteValue_ReadWrite_NullChannel_Index2);
 CPPUNIT_TEST(testAGN934XNI_ATTR_INSTRUMENT_MODE_DiscreteValue_ReadWrite_NullChannel_Index3);

	CPPUNIT_TEST(testAGN934XNI_ATTR_AMPLITUDE_UNITS_defaultValue_ReadWrite_NullChannel_Index0);
	CPPUNIT_TEST(testAGN934XNI_ATTR_AMPLITUDE_UNITS_DiscreteValue_ReadWrite_NullChannel_Index1);
	CPPUNIT_TEST(testAGN934XNI_ATTR_AMPLITUDE_UNITS_DiscreteValue_ReadWrite_NullChannel_Index2);
	CPPUNIT_TEST(testAGN934XNI_ATTR_AMPLITUDE_UNITS_DiscreteValue_ReadWrite_NullChannel_Index3);
	CPPUNIT_TEST(testAGN934XNI_ATTR_AMPLITUDE_UNITS_DiscreteValue_ReadWrite_NullChannel_Index4);
	CPPUNIT_TEST(testAGN934XNI_ATTR_AMPLITUDE_UNITS_DiscreteValue_ReadWrite_NullChannel_Index5);
	CPPUNIT_TEST(testAGN934XNI_ATTR_AMPLITUDE_UNITS_DiscreteValue_ReadWrite_NullChannel_Index6);
	CPPUNIT_TEST(testAGN934XNI_ATTR_AMPLITUDE_UNITS_DiscreteValue_ReadWrite_NullChannel_Index7);
	CPPUNIT_TEST(testAGN934XNI_ATTR_AMPLITUDE_UNITS_DiscreteValue_ReadWrite_NullChannel_Index8);

	CPPUNIT_TEST(testAGN934XNI_ATTR_ATTENUATION_defaultValue_ReadWrite_NullChannel_Index0);

	CPPUNIT_TEST(testAGN934XNI_ATTR_ATTENUATION_AUTO_defaultValue_ReadWrite_NullChannel_Index0);

	CPPUNIT_TEST(testAGN934XNI_ATTR_DETECTOR_TYPE_defaultValue_ReadWrite_REP_1_Index0);
	CPPUNIT_TEST(testAGN934XNI_ATTR_DETECTOR_TYPE_DiscreteValue_ReadWrite_REP_1_Index1);
	CPPUNIT_TEST(testAGN934XNI_ATTR_DETECTOR_TYPE_DiscreteValue_ReadWrite_REP_1_Index2);
	CPPUNIT_TEST(testAGN934XNI_ATTR_DETECTOR_TYPE_DiscreteValue_ReadWrite_REP_1_Index3);
    CPPUNIT_TEST(testAGN934XNI_ATTR_DETECTOR_TYPE_DiscreteValue_ReadWrite_REP_1_Index4);
	CPPUNIT_TEST(testAGN934XNI_ATTR_DETECTOR_TYPE_DiscreteValue_ReadWrite_REP_1_Index5);

	CPPUNIT_TEST(testAGN934XNI_ATTR_DETECTOR_TYPE_defaultValue_ReadWrite_REP_2_Index0);
	CPPUNIT_TEST(testAGN934XNI_ATTR_DETECTOR_TYPE_DiscreteValue_ReadWrite_REP_2_Index1);
	CPPUNIT_TEST(testAGN934XNI_ATTR_DETECTOR_TYPE_DiscreteValue_ReadWrite_REP_2_Index2);
	CPPUNIT_TEST(testAGN934XNI_ATTR_DETECTOR_TYPE_DiscreteValue_ReadWrite_REP_2_Index3);
	CPPUNIT_TEST(testAGN934XNI_ATTR_DETECTOR_TYPE_DiscreteValue_ReadWrite_REP_2_Index4);
	CPPUNIT_TEST(testAGN934XNI_ATTR_DETECTOR_TYPE_DiscreteValue_ReadWrite_REP_2_Index5);

	CPPUNIT_TEST(testAGN934XNI_ATTR_DETECTOR_TYPE_defaultValue_ReadWrite_REP_3_Index0);
	CPPUNIT_TEST(testAGN934XNI_ATTR_DETECTOR_TYPE_DiscreteValue_ReadWrite_REP_3_Index1);
	CPPUNIT_TEST(testAGN934XNI_ATTR_DETECTOR_TYPE_DiscreteValue_ReadWrite_REP_3_Index2);
	CPPUNIT_TEST(testAGN934XNI_ATTR_DETECTOR_TYPE_DiscreteValue_ReadWrite_REP_3_Index3);
	CPPUNIT_TEST(testAGN934XNI_ATTR_DETECTOR_TYPE_DiscreteValue_ReadWrite_REP_3_Index4);
	CPPUNIT_TEST(testAGN934XNI_ATTR_DETECTOR_TYPE_DiscreteValue_ReadWrite_REP_3_Index5);

	CPPUNIT_TEST(testAGN934XNI_ATTR_DETECTOR_TYPE_defaultValue_ReadWrite_REP_4_Index0);
	CPPUNIT_TEST(testAGN934XNI_ATTR_DETECTOR_TYPE_DiscreteValue_ReadWrite_REP_4_Index1);
	CPPUNIT_TEST(testAGN934XNI_ATTR_DETECTOR_TYPE_DiscreteValue_ReadWrite_REP_4_Index2);
	CPPUNIT_TEST(testAGN934XNI_ATTR_DETECTOR_TYPE_DiscreteValue_ReadWrite_REP_4_Index3);
	CPPUNIT_TEST(testAGN934XNI_ATTR_DETECTOR_TYPE_DiscreteValue_ReadWrite_REP_4_Index4);
	CPPUNIT_TEST(testAGN934XNI_ATTR_DETECTOR_TYPE_DiscreteValue_ReadWrite_REP_4_Index5);

	CPPUNIT_TEST(testAGN934XNI_ATTR_FREQUENCY_START_defaultValue_ReadWrite_NullChannel_Index0);

	CPPUNIT_TEST(testAGN934XNI_ATTR_FREQUENCY_STOP_defaultValue_ReadWrite_NullChannel_Index0);

	CPPUNIT_TEST(testAGN934XNI_ATTR_FREQUENCY_OFFSET_defaultValue_ReadWrite_NullChannel_Index0);

	CPPUNIT_TEST(testAGN934XNI_ATTR_INPUT_IMPEDANCE_defaultValue_ReadWrite_NullChannel_Index0);
	CPPUNIT_TEST(testAGN934XNI_ATTR_INPUT_IMPEDANCE_DiscreteValue_ReadWrite_NullChannel_Index1);
	CPPUNIT_TEST(testAGN934XNI_ATTR_INPUT_IMPEDANCE_DiscreteValue_ReadWrite_NullChannel_Index2);

	CPPUNIT_TEST(testAGN934XNI_ATTR_CENTER_FREQUENCY_defaultValue_ReadWrite_NullChannel_Index0);

	CPPUNIT_TEST(testAGN934XNI_ATTR_FREQUENCY_SPAN_defaultValue_ReadWrite_NullChannel_Index0);

	CPPUNIT_TEST(testAGN934XNI_ATTR_REFERENCE_LEVEL_defaultValue_ReadWrite_NullChannel_Index0);
	CPPUNIT_TEST(testAGN934XNI_ATTR_REFERENCE_LEVEL_CloseminimumValue_ReadWrite_NullChannel_Index1);
	CPPUNIT_TEST(testAGN934XNI_ATTR_REFERENCE_LEVEL_ClosemaximumValue_ReadWrite_NullChannel_Index1);
	CPPUNIT_TEST(testAGN934XNI_ATTR_REFERENCE_LEVEL_RandomValue_ReadWrite_NullChannel_Index1);
	CPPUNIT_TEST(testAGN934XNI_ATTR_REFERENCE_LEVEL_ViolationMinValue_ReadWrite_NullChannel_Index1);
	CPPUNIT_TEST(testAGN934XNI_ATTR_REFERENCE_LEVEL_ViolationMaxValue_ReadWrite_NullChannel_Index1);

	CPPUNIT_TEST(testAGN934XNI_ATTR_REFERENCE_LEVEL_OFFSET_defaultValue_ReadWrite_NullChannel_Index0);
//	CPPUNIT_TEST(testAGN934XNI_ATTR_REFERENCE_LEVEL_OFFSET_CloseminimumValue_ReadWrite_NullChannel_Index1);
//	CPPUNIT_TEST(testAGN934XNI_ATTR_REFERENCE_LEVEL_OFFSET_ClosemaximumValue_ReadWrite_NullChannel_Index1);
//	CPPUNIT_TEST(testAGN934XNI_ATTR_REFERENCE_LEVEL_OFFSET_RandomValue_ReadWrite_NullChannel_Index1);
//	CPPUNIT_TEST(testAGN934XNI_ATTR_REFERENCE_LEVEL_OFFSET_ViolationMinValue_ReadWrite_NullChannel_Index1);
//	CPPUNIT_TEST(testAGN934XNI_ATTR_REFERENCE_LEVEL_OFFSET_ViolationMaxValue_ReadWrite_NullChannel_Index1);


	CPPUNIT_TEST(testAGN934XNI_ATTR_RESOLUTION_BANDWIDTH_defaultValue_ReadWrite_NullChannel_Index0);
//	CPPUNIT_TEST(testAGN934XNI_ATTR_RESOLUTION_BANDWIDTH_CloseminimumValue_ReadWrite_NullChannel_Index1);
	CPPUNIT_TEST(testAGN934XNI_ATTR_RESOLUTION_BANDWIDTH_ClosemaximumValue_ReadWrite_NullChannel_Index1);
//	CPPUNIT_TEST(testAGN934XNI_ATTR_RESOLUTION_BANDWIDTH_RandomValue_ReadWrite_NullChannel_Index1);
	CPPUNIT_TEST(testAGN934XNI_ATTR_RESOLUTION_BANDWIDTH_ViolationMinValue_ReadWrite_NullChannel_Index1);
	CPPUNIT_TEST(testAGN934XNI_ATTR_RESOLUTION_BANDWIDTH_ViolationMaxValue_ReadWrite_NullChannel_Index1);

	CPPUNIT_TEST(testAGN934XNI_ATTR_RESOLUTION_BANDWIDTH_AUTO_defaultValue_ReadWrite_NullChannel_Index0);

	CPPUNIT_TEST(testAGN934XNI_ATTR_SWEEP_MODE_CONTINUOUS_defaultValue_ReadWrite_NullChannel_Index0);

	CPPUNIT_TEST(testAGN934XNI_ATTR_SWEEP_TIME_defaultValue_ReadWrite_NullChannel_Index0);

//	CPPUNIT_TEST(testAGN934XNI_ATTR_SWEEP_MODE_defaultValue_ReadWrite_NullChannel_Index0);
	CPPUNIT_TEST(testAGN934XNI_ATTR_SWEEP_MODE_DiscreteValue_ReadWrite_NullChannel_Index1);
	CPPUNIT_TEST(testAGN934XNI_ATTR_SWEEP_MODE_DiscreteValue_ReadWrite_NullChannel_Index2);
//	CPPUNIT_TEST(testAGN934XNI_ATTR_SWEEP_MODE_DiscreteValue_ReadWrite_NullChannel_Index3);

//	CPPUNIT_TEST(testAGN934XNI_ATTR_SWEEP_TIME_AUTO_defaultValue_ReadWrite_NullChannel_Index0);

	CPPUNIT_TEST(testAGN934XNI_ATTR_TRACE_COUNT_defaultValue_ReadOnly_NullChannel_Index0);

	CPPUNIT_TEST(testAGN934XNI_ATTR_TRACE_SIZE_defaultValue_ReadOnly_REP_1_Index0);

	CPPUNIT_TEST(testAGN934XNI_ATTR_TRACE_SIZE_defaultValue_ReadOnly_REP_2_Index0);

	CPPUNIT_TEST(testAGN934XNI_ATTR_TRACE_SIZE_defaultValue_ReadOnly_REP_3_Index0);

	CPPUNIT_TEST(testAGN934XNI_ATTR_TRACE_SIZE_defaultValue_ReadOnly_REP_4_Index0);

	CPPUNIT_TEST(testAGN934XNI_ATTR_TRACE_TYPE_defaultValue_ReadWrite_REP_1_Index0);
	CPPUNIT_TEST(testAGN934XNI_ATTR_TRACE_TYPE_DiscreteValue_ReadWrite_REP_1_Index1);
	CPPUNIT_TEST(testAGN934XNI_ATTR_TRACE_TYPE_DiscreteValue_ReadWrite_REP_1_Index2);
	CPPUNIT_TEST(testAGN934XNI_ATTR_TRACE_TYPE_DiscreteValue_ReadWrite_REP_1_Index3);
	CPPUNIT_TEST(testAGN934XNI_ATTR_TRACE_TYPE_DiscreteValue_ReadWrite_REP_1_Index4);
	CPPUNIT_TEST(testAGN934XNI_ATTR_TRACE_TYPE_DiscreteValue_ReadWrite_REP_1_Index5);

	CPPUNIT_TEST(testAGN934XNI_ATTR_TRACE_TYPE_defaultValue_ReadWrite_REP_2_Index0);
	CPPUNIT_TEST(testAGN934XNI_ATTR_TRACE_TYPE_DiscreteValue_ReadWrite_REP_2_Index1);
	CPPUNIT_TEST(testAGN934XNI_ATTR_TRACE_TYPE_DiscreteValue_ReadWrite_REP_2_Index2);
	CPPUNIT_TEST(testAGN934XNI_ATTR_TRACE_TYPE_DiscreteValue_ReadWrite_REP_2_Index3);
	CPPUNIT_TEST(testAGN934XNI_ATTR_TRACE_TYPE_DiscreteValue_ReadWrite_REP_2_Index4);
	CPPUNIT_TEST(testAGN934XNI_ATTR_TRACE_TYPE_DiscreteValue_ReadWrite_REP_2_Index5);

	CPPUNIT_TEST(testAGN934XNI_ATTR_TRACE_TYPE_defaultValue_ReadWrite_REP_3_Index0);
	CPPUNIT_TEST(testAGN934XNI_ATTR_TRACE_TYPE_DiscreteValue_ReadWrite_REP_3_Index1);
	CPPUNIT_TEST(testAGN934XNI_ATTR_TRACE_TYPE_DiscreteValue_ReadWrite_REP_3_Index2);
	CPPUNIT_TEST(testAGN934XNI_ATTR_TRACE_TYPE_DiscreteValue_ReadWrite_REP_3_Index3);
	CPPUNIT_TEST(testAGN934XNI_ATTR_TRACE_TYPE_DiscreteValue_ReadWrite_REP_3_Index4);
	CPPUNIT_TEST(testAGN934XNI_ATTR_TRACE_TYPE_DiscreteValue_ReadWrite_REP_3_Index5);

	CPPUNIT_TEST(testAGN934XNI_ATTR_TRACE_TYPE_defaultValue_ReadWrite_REP_4_Index0);
	CPPUNIT_TEST(testAGN934XNI_ATTR_TRACE_TYPE_DiscreteValue_ReadWrite_REP_4_Index1);
	CPPUNIT_TEST(testAGN934XNI_ATTR_TRACE_TYPE_DiscreteValue_ReadWrite_REP_4_Index2);
	CPPUNIT_TEST(testAGN934XNI_ATTR_TRACE_TYPE_DiscreteValue_ReadWrite_REP_4_Index3);
	CPPUNIT_TEST(testAGN934XNI_ATTR_TRACE_TYPE_DiscreteValue_ReadWrite_REP_4_Index4);
	CPPUNIT_TEST(testAGN934XNI_ATTR_TRACE_TYPE_DiscreteValue_ReadWrite_REP_4_Index5);

	CPPUNIT_TEST(testAGN934XNI_ATTR_VERTICAL_SCALE_defaultValue_ReadWrite_NullChannel_Index0);
	CPPUNIT_TEST(testAGN934XNI_ATTR_VERTICAL_SCALE_DiscreteValue_ReadWrite_NullChannel_Index1);
	CPPUNIT_TEST(testAGN934XNI_ATTR_VERTICAL_SCALE_DiscreteValue_ReadWrite_NullChannel_Index2);

	CPPUNIT_TEST(testAGN934XNI_ATTR_VIDEO_BANDWIDTH_defaultValue_ReadWrite_NullChannel_Index0);
//	CPPUNIT_TEST(testAGN934XNI_ATTR_VIDEO_BANDWIDTH_CloseminimumValue_ReadWrite_NullChannel_Index1);
	CPPUNIT_TEST(testAGN934XNI_ATTR_VIDEO_BANDWIDTH_ClosemaximumValue_ReadWrite_NullChannel_Index1);
//	CPPUNIT_TEST(testAGN934XNI_ATTR_VIDEO_BANDWIDTH_RandomValue_ReadWrite_NullChannel_Index1);
	CPPUNIT_TEST(testAGN934XNI_ATTR_VIDEO_BANDWIDTH_ViolationMinValue_ReadWrite_NullChannel_Index1);
	CPPUNIT_TEST(testAGN934XNI_ATTR_VIDEO_BANDWIDTH_ViolationMaxValue_ReadWrite_NullChannel_Index1);

	CPPUNIT_TEST(testAGN934XNI_ATTR_VIDEO_BANDWIDTH_AUTO_defaultValue_ReadWrite_NullChannel_Index0);

	CPPUNIT_TEST_SUITE_END();

public:
	void setUp();
	void tearDown();	

	void testAGN934XNI_ATTR_ACTIVE_TRACE_defaultValue_ReadWrite_NullChannel_Index0();

	void testAGN934XNI_ATTR_TRACE_MATH_TYPE_defaultValue_ReadWrite_NullChannel_Index0();
	void testAGN934XNI_ATTR_TRACE_MATH_TYPE_DiscreteValue_ReadWrite_NullChannel_Index1();
	void testAGN934XNI_ATTR_TRACE_MATH_TYPE_DiscreteValue_ReadWrite_NullChannel_Index2();

	void testAGN934XNI_ATTR_HIGH_SENSITIVITY_ENABLE_defaultValue_ReadWrite_NullChannel_Index0();

	void testAGN934XNI_ATTR_VBW_RBW_RATIO_AUTO_defaultValue_ReadWrite_NullChannel_Index0();

	void testAGN934XNI_ATTR_VBW_RBW_RATIO_defaultValue_ReadWrite_NullChannel_Index0();
	void testAGN934XNI_ATTR_VBW_RBW_RATIO_CloseminimumValue_ReadWrite_NullChannel_Index1();
	void testAGN934XNI_ATTR_VBW_RBW_RATIO_ClosemaximumValue_ReadWrite_NullChannel_Index1();
	void testAGN934XNI_ATTR_VBW_RBW_RATIO_RandomValue_ReadWrite_NullChannel_Index1();
	void testAGN934XNI_ATTR_VBW_RBW_RATIO_ViolationMinValue_ReadWrite_NullChannel_Index1();
	void testAGN934XNI_ATTR_VBW_RBW_RATIO_ViolationMaxValue_ReadWrite_NullChannel_Index1();

	void testAGN934XNI_ATTR_AVERAGE_DURATION_ENABLE_defaultValue_ReadWrite_REP_1_Index0();

	void testAGN934XNI_ATTR_AVERAGE_DURATION_ENABLE_defaultValue_ReadWrite_REP_2_Index0();

	void testAGN934XNI_ATTR_AVERAGE_DURATION_ENABLE_defaultValue_ReadWrite_REP_3_Index0();

	void testAGN934XNI_ATTR_AVERAGE_DURATION_ENABLE_defaultValue_ReadWrite_REP_4_Index0();

	void testAGN934XNI_ATTR_AVERAGE_DURATION_defaultValue_ReadWrite_REP_1_Index0();

	void testAGN934XNI_ATTR_AVERAGE_DURATION_defaultValue_ReadWrite_REP_2_Index0();

	void testAGN934XNI_ATTR_AVERAGE_DURATION_defaultValue_ReadWrite_REP_3_Index0();

	void testAGN934XNI_ATTR_AVERAGE_DURATION_defaultValue_ReadWrite_REP_4_Index0();

	void testAGN934XNI_ATTR_AVERAGE_TYPE_defaultValue_ReadWrite_NullChannel_Index0();
	void testAGN934XNI_ATTR_AVERAGE_TYPE_DiscreteValue_ReadWrite_NullChannel_Index1();
	void testAGN934XNI_ATTR_AVERAGE_TYPE_DiscreteValue_ReadWrite_NullChannel_Index2();
	void testAGN934XNI_ATTR_AVERAGE_TYPE_DiscreteValue_ReadWrite_NullChannel_Index3();

	void testAGN934XNI_ATTR_AVERAGE_ENABLE_defaultValue_ReadWrite_REP_1_Index0();

	void testAGN934XNI_ATTR_AVERAGE_ENABLE_defaultValue_ReadWrite_REP_2_Index0();

	void testAGN934XNI_ATTR_AVERAGE_ENABLE_defaultValue_ReadWrite_REP_3_Index0();

	void testAGN934XNI_ATTR_AVERAGE_ENABLE_defaultValue_ReadWrite_REP_4_Index0();

	void testAGN934XNI_ATTR_AVERAGE_COUNT_defaultValue_ReadWrite_REP_1_Index0();
	void testAGN934XNI_ATTR_AVERAGE_COUNT_CloseminimumValue_ReadWrite_REP_1_Index1();
	void testAGN934XNI_ATTR_AVERAGE_COUNT_ClosemaximumValue_ReadWrite_REP_1_Index1();
	void testAGN934XNI_ATTR_AVERAGE_COUNT_RandomValue_ReadWrite_REP_1_Index1();
	void testAGN934XNI_ATTR_AVERAGE_COUNT_ViolationMinValue_ReadWrite_REP_1_Index1();
	void testAGN934XNI_ATTR_AVERAGE_COUNT_ViolationMaxValue_ReadWrite_REP_1_Index1();

	void testAGN934XNI_ATTR_AVERAGE_COUNT_defaultValue_ReadWrite_REP_2_Index0();
	void testAGN934XNI_ATTR_AVERAGE_COUNT_CloseminimumValue_ReadWrite_REP_2_Index1();
	void testAGN934XNI_ATTR_AVERAGE_COUNT_ClosemaximumValue_ReadWrite_REP_2_Index1();
	void testAGN934XNI_ATTR_AVERAGE_COUNT_RandomValue_ReadWrite_REP_2_Index1();
	void testAGN934XNI_ATTR_AVERAGE_COUNT_ViolationMinValue_ReadWrite_REP_2_Index1();
	void testAGN934XNI_ATTR_AVERAGE_COUNT_ViolationMaxValue_ReadWrite_REP_2_Index1();

	void testAGN934XNI_ATTR_AVERAGE_COUNT_defaultValue_ReadWrite_REP_3_Index0();
	void testAGN934XNI_ATTR_AVERAGE_COUNT_CloseminimumValue_ReadWrite_REP_3_Index1();
	void testAGN934XNI_ATTR_AVERAGE_COUNT_ClosemaximumValue_ReadWrite_REP_3_Index1();
	void testAGN934XNI_ATTR_AVERAGE_COUNT_RandomValue_ReadWrite_REP_3_Index1();
	void testAGN934XNI_ATTR_AVERAGE_COUNT_ViolationMinValue_ReadWrite_REP_3_Index1();
	void testAGN934XNI_ATTR_AVERAGE_COUNT_ViolationMaxValue_ReadWrite_REP_3_Index1();

	void testAGN934XNI_ATTR_AVERAGE_COUNT_defaultValue_ReadWrite_REP_4_Index0();
	void testAGN934XNI_ATTR_AVERAGE_COUNT_CloseminimumValue_ReadWrite_REP_4_Index1();
	void testAGN934XNI_ATTR_AVERAGE_COUNT_ClosemaximumValue_ReadWrite_REP_4_Index1();
	void testAGN934XNI_ATTR_AVERAGE_COUNT_RandomValue_ReadWrite_REP_4_Index1();
	void testAGN934XNI_ATTR_AVERAGE_COUNT_ViolationMinValue_ReadWrite_REP_4_Index1();
	void testAGN934XNI_ATTR_AVERAGE_COUNT_ViolationMaxValue_ReadWrite_REP_4_Index1();

	void testAGN934XNI_ATTR_MEASUREMENT_TYPE_defaultValue_ReadWrite_NullChannel_Index0();
	void testAGN934XNI_ATTR_MEASUREMENT_TYPE_DiscreteValue_ReadWrite_NullChannel_Index1();
	void testAGN934XNI_ATTR_MEASUREMENT_TYPE_DiscreteValue_ReadWrite_NullChannel_Index2();
	void testAGN934XNI_ATTR_MEASUREMENT_TYPE_DiscreteValue_ReadWrite_NullChannel_Index3();
	void testAGN934XNI_ATTR_MEASUREMENT_TYPE_DiscreteValue_ReadWrite_NullChannel_Index4();
	void testAGN934XNI_ATTR_MEASUREMENT_TYPE_DiscreteValue_ReadWrite_NullChannel_Index5();

	void testAGN934XNI_ATTR_INSTRUMENT_MODE_defaultValue_ReadWrite_NullChannel_Index0();
	void testAGN934XNI_ATTR_INSTRUMENT_MODE_DiscreteValue_ReadWrite_NullChannel_Index1();
	void testAGN934XNI_ATTR_INSTRUMENT_MODE_DiscreteValue_ReadWrite_NullChannel_Index2();
	void testAGN934XNI_ATTR_INSTRUMENT_MODE_DiscreteValue_ReadWrite_NullChannel_Index3();

	void testAGN934XNI_ATTR_AMPLITUDE_UNITS_defaultValue_ReadWrite_NullChannel_Index0();
	void testAGN934XNI_ATTR_AMPLITUDE_UNITS_DiscreteValue_ReadWrite_NullChannel_Index1();
	void testAGN934XNI_ATTR_AMPLITUDE_UNITS_DiscreteValue_ReadWrite_NullChannel_Index2();
	void testAGN934XNI_ATTR_AMPLITUDE_UNITS_DiscreteValue_ReadWrite_NullChannel_Index3();
	void testAGN934XNI_ATTR_AMPLITUDE_UNITS_DiscreteValue_ReadWrite_NullChannel_Index4();
	void testAGN934XNI_ATTR_AMPLITUDE_UNITS_DiscreteValue_ReadWrite_NullChannel_Index5();
	void testAGN934XNI_ATTR_AMPLITUDE_UNITS_DiscreteValue_ReadWrite_NullChannel_Index6();
	void testAGN934XNI_ATTR_AMPLITUDE_UNITS_DiscreteValue_ReadWrite_NullChannel_Index7();
	void testAGN934XNI_ATTR_AMPLITUDE_UNITS_DiscreteValue_ReadWrite_NullChannel_Index8();

	void testAGN934XNI_ATTR_ATTENUATION_defaultValue_ReadWrite_NullChannel_Index0();

	void testAGN934XNI_ATTR_ATTENUATION_AUTO_defaultValue_ReadWrite_NullChannel_Index0();

	void testAGN934XNI_ATTR_DETECTOR_TYPE_defaultValue_ReadWrite_NullChannel_Index0();
	void testAGN934XNI_ATTR_DETECTOR_TYPE_DiscreteValue_ReadWrite_NullChannel_Index1();
	void testAGN934XNI_ATTR_DETECTOR_TYPE_DiscreteValue_ReadWrite_NullChannel_Index2();
	void testAGN934XNI_ATTR_DETECTOR_TYPE_DiscreteValue_ReadWrite_NullChannel_Index3();
	void testAGN934XNI_ATTR_DETECTOR_TYPE_DiscreteValue_ReadWrite_NullChannel_Index4();
	void testAGN934XNI_ATTR_DETECTOR_TYPE_DiscreteValue_ReadWrite_NullChannel_Index5();

	void testAGN934XNI_ATTR_DETECTOR_TYPE_defaultValue_ReadWrite_REP_1_Index0();
	void testAGN934XNI_ATTR_DETECTOR_TYPE_DiscreteValue_ReadWrite_REP_1_Index1();
	void testAGN934XNI_ATTR_DETECTOR_TYPE_DiscreteValue_ReadWrite_REP_1_Index2();
	void testAGN934XNI_ATTR_DETECTOR_TYPE_DiscreteValue_ReadWrite_REP_1_Index3();
	void testAGN934XNI_ATTR_DETECTOR_TYPE_DiscreteValue_ReadWrite_REP_1_Index4();
	void testAGN934XNI_ATTR_DETECTOR_TYPE_DiscreteValue_ReadWrite_REP_1_Index5();

	void testAGN934XNI_ATTR_DETECTOR_TYPE_defaultValue_ReadWrite_REP_2_Index0();
	void testAGN934XNI_ATTR_DETECTOR_TYPE_DiscreteValue_ReadWrite_REP_2_Index1();
	void testAGN934XNI_ATTR_DETECTOR_TYPE_DiscreteValue_ReadWrite_REP_2_Index2();
	void testAGN934XNI_ATTR_DETECTOR_TYPE_DiscreteValue_ReadWrite_REP_2_Index3();
	void testAGN934XNI_ATTR_DETECTOR_TYPE_DiscreteValue_ReadWrite_REP_2_Index4();
	void testAGN934XNI_ATTR_DETECTOR_TYPE_DiscreteValue_ReadWrite_REP_2_Index5();

	void testAGN934XNI_ATTR_DETECTOR_TYPE_defaultValue_ReadWrite_REP_3_Index0();
	void testAGN934XNI_ATTR_DETECTOR_TYPE_DiscreteValue_ReadWrite_REP_3_Index1();
	void testAGN934XNI_ATTR_DETECTOR_TYPE_DiscreteValue_ReadWrite_REP_3_Index2();
	void testAGN934XNI_ATTR_DETECTOR_TYPE_DiscreteValue_ReadWrite_REP_3_Index3();
	void testAGN934XNI_ATTR_DETECTOR_TYPE_DiscreteValue_ReadWrite_REP_3_Index4();
	void testAGN934XNI_ATTR_DETECTOR_TYPE_DiscreteValue_ReadWrite_REP_3_Index5();

	void testAGN934XNI_ATTR_DETECTOR_TYPE_defaultValue_ReadWrite_REP_4_Index0();
	void testAGN934XNI_ATTR_DETECTOR_TYPE_DiscreteValue_ReadWrite_REP_4_Index1();
	void testAGN934XNI_ATTR_DETECTOR_TYPE_DiscreteValue_ReadWrite_REP_4_Index2();
	void testAGN934XNI_ATTR_DETECTOR_TYPE_DiscreteValue_ReadWrite_REP_4_Index3();
	void testAGN934XNI_ATTR_DETECTOR_TYPE_DiscreteValue_ReadWrite_REP_4_Index4();
	void testAGN934XNI_ATTR_DETECTOR_TYPE_DiscreteValue_ReadWrite_REP_4_Index5();

	void testAGN934XNI_ATTR_FREQUENCY_START_defaultValue_ReadWrite_NullChannel_Index0();

	void testAGN934XNI_ATTR_FREQUENCY_STOP_defaultValue_ReadWrite_NullChannel_Index0();

	void testAGN934XNI_ATTR_FREQUENCY_OFFSET_defaultValue_ReadWrite_NullChannel_Index0();

	void testAGN934XNI_ATTR_INPUT_IMPEDANCE_defaultValue_ReadWrite_NullChannel_Index0();
	void testAGN934XNI_ATTR_INPUT_IMPEDANCE_DiscreteValue_ReadWrite_NullChannel_Index1();
	void testAGN934XNI_ATTR_INPUT_IMPEDANCE_DiscreteValue_ReadWrite_NullChannel_Index2();

	void testAGN934XNI_ATTR_CENTER_FREQUENCY_defaultValue_ReadWrite_NullChannel_Index0();

	void testAGN934XNI_ATTR_FREQUENCY_SPAN_defaultValue_ReadWrite_NullChannel_Index0();

	void testAGN934XNI_ATTR_REFERENCE_LEVEL_defaultValue_ReadWrite_NullChannel_Index0();
	void testAGN934XNI_ATTR_REFERENCE_LEVEL_CloseminimumValue_ReadWrite_NullChannel_Index1();
	void testAGN934XNI_ATTR_REFERENCE_LEVEL_ClosemaximumValue_ReadWrite_NullChannel_Index1();
	void testAGN934XNI_ATTR_REFERENCE_LEVEL_RandomValue_ReadWrite_NullChannel_Index1();
	void testAGN934XNI_ATTR_REFERENCE_LEVEL_ViolationMinValue_ReadWrite_NullChannel_Index1();
	void testAGN934XNI_ATTR_REFERENCE_LEVEL_ViolationMaxValue_ReadWrite_NullChannel_Index1();

	void testAGN934XNI_ATTR_REFERENCE_LEVEL_OFFSET_defaultValue_ReadWrite_NullChannel_Index0();
	void testAGN934XNI_ATTR_REFERENCE_LEVEL_OFFSET_CloseminimumValue_ReadWrite_NullChannel_Index1();
	void testAGN934XNI_ATTR_REFERENCE_LEVEL_OFFSET_ClosemaximumValue_ReadWrite_NullChannel_Index1();
	void testAGN934XNI_ATTR_REFERENCE_LEVEL_OFFSET_RandomValue_ReadWrite_NullChannel_Index1();
	void testAGN934XNI_ATTR_REFERENCE_LEVEL_OFFSET_ViolationMinValue_ReadWrite_NullChannel_Index1();
	void testAGN934XNI_ATTR_REFERENCE_LEVEL_OFFSET_ViolationMaxValue_ReadWrite_NullChannel_Index1();

	void testAGN934XNI_ATTR_RESOLUTION_BANDWIDTH_defaultValue_ReadWrite_NullChannel_Index0();
	void testAGN934XNI_ATTR_RESOLUTION_BANDWIDTH_CloseminimumValue_ReadWrite_NullChannel_Index1();
	void testAGN934XNI_ATTR_RESOLUTION_BANDWIDTH_ClosemaximumValue_ReadWrite_NullChannel_Index1();
	void testAGN934XNI_ATTR_RESOLUTION_BANDWIDTH_RandomValue_ReadWrite_NullChannel_Index1();
	void testAGN934XNI_ATTR_RESOLUTION_BANDWIDTH_ViolationMinValue_ReadWrite_NullChannel_Index1();
	void testAGN934XNI_ATTR_RESOLUTION_BANDWIDTH_ViolationMaxValue_ReadWrite_NullChannel_Index1();

	void testAGN934XNI_ATTR_RESOLUTION_BANDWIDTH_AUTO_defaultValue_ReadWrite_NullChannel_Index0();

	void testAGN934XNI_ATTR_SWEEP_MODE_CONTINUOUS_defaultValue_ReadWrite_NullChannel_Index0();

	void testAGN934XNI_ATTR_SWEEP_TIME_defaultValue_ReadWrite_NullChannel_Index0();

	void testAGN934XNI_ATTR_SWEEP_MODE_defaultValue_ReadWrite_NullChannel_Index0();
	void testAGN934XNI_ATTR_SWEEP_MODE_DiscreteValue_ReadWrite_NullChannel_Index1();
	void testAGN934XNI_ATTR_SWEEP_MODE_DiscreteValue_ReadWrite_NullChannel_Index2();
	void testAGN934XNI_ATTR_SWEEP_MODE_DiscreteValue_ReadWrite_NullChannel_Index3();

	void testAGN934XNI_ATTR_SWEEP_TIME_AUTO_defaultValue_ReadWrite_NullChannel_Index0();

	void testAGN934XNI_ATTR_TRACE_COUNT_defaultValue_ReadOnly_NullChannel_Index0();

	void testAGN934XNI_ATTR_TRACE_SIZE_defaultValue_ReadOnly_REP_1_Index0();

	void testAGN934XNI_ATTR_TRACE_SIZE_defaultValue_ReadOnly_REP_2_Index0();

	void testAGN934XNI_ATTR_TRACE_SIZE_defaultValue_ReadOnly_REP_3_Index0();

	void testAGN934XNI_ATTR_TRACE_SIZE_defaultValue_ReadOnly_REP_4_Index0();

	void testAGN934XNI_ATTR_TRACE_TYPE_defaultValue_ReadWrite_REP_1_Index0();
	void testAGN934XNI_ATTR_TRACE_TYPE_DiscreteValue_ReadWrite_REP_1_Index1();
	void testAGN934XNI_ATTR_TRACE_TYPE_DiscreteValue_ReadWrite_REP_1_Index2();
	void testAGN934XNI_ATTR_TRACE_TYPE_DiscreteValue_ReadWrite_REP_1_Index3();
	void testAGN934XNI_ATTR_TRACE_TYPE_DiscreteValue_ReadWrite_REP_1_Index4();
	void testAGN934XNI_ATTR_TRACE_TYPE_DiscreteValue_ReadWrite_REP_1_Index5();

	void testAGN934XNI_ATTR_TRACE_TYPE_defaultValue_ReadWrite_REP_2_Index0();
	void testAGN934XNI_ATTR_TRACE_TYPE_DiscreteValue_ReadWrite_REP_2_Index1();
	void testAGN934XNI_ATTR_TRACE_TYPE_DiscreteValue_ReadWrite_REP_2_Index2();
	void testAGN934XNI_ATTR_TRACE_TYPE_DiscreteValue_ReadWrite_REP_2_Index3();
	void testAGN934XNI_ATTR_TRACE_TYPE_DiscreteValue_ReadWrite_REP_2_Index4();
	void testAGN934XNI_ATTR_TRACE_TYPE_DiscreteValue_ReadWrite_REP_2_Index5();

	void testAGN934XNI_ATTR_TRACE_TYPE_defaultValue_ReadWrite_REP_3_Index0();
	void testAGN934XNI_ATTR_TRACE_TYPE_DiscreteValue_ReadWrite_REP_3_Index1();
	void testAGN934XNI_ATTR_TRACE_TYPE_DiscreteValue_ReadWrite_REP_3_Index2();
	void testAGN934XNI_ATTR_TRACE_TYPE_DiscreteValue_ReadWrite_REP_3_Index3();
	void testAGN934XNI_ATTR_TRACE_TYPE_DiscreteValue_ReadWrite_REP_3_Index4();
	void testAGN934XNI_ATTR_TRACE_TYPE_DiscreteValue_ReadWrite_REP_3_Index5();

	void testAGN934XNI_ATTR_TRACE_TYPE_defaultValue_ReadWrite_REP_4_Index0();
	void testAGN934XNI_ATTR_TRACE_TYPE_DiscreteValue_ReadWrite_REP_4_Index1();
	void testAGN934XNI_ATTR_TRACE_TYPE_DiscreteValue_ReadWrite_REP_4_Index2();
	void testAGN934XNI_ATTR_TRACE_TYPE_DiscreteValue_ReadWrite_REP_4_Index3();
	void testAGN934XNI_ATTR_TRACE_TYPE_DiscreteValue_ReadWrite_REP_4_Index4();
	void testAGN934XNI_ATTR_TRACE_TYPE_DiscreteValue_ReadWrite_REP_4_Index5();

	void testAGN934XNI_ATTR_VERTICAL_SCALE_defaultValue_ReadWrite_NullChannel_Index0();
	void testAGN934XNI_ATTR_VERTICAL_SCALE_DiscreteValue_ReadWrite_NullChannel_Index1();
	void testAGN934XNI_ATTR_VERTICAL_SCALE_DiscreteValue_ReadWrite_NullChannel_Index2();

	void testAGN934XNI_ATTR_VIDEO_BANDWIDTH_defaultValue_ReadWrite_NullChannel_Index0();
	void testAGN934XNI_ATTR_VIDEO_BANDWIDTH_CloseminimumValue_ReadWrite_NullChannel_Index1();
	void testAGN934XNI_ATTR_VIDEO_BANDWIDTH_ClosemaximumValue_ReadWrite_NullChannel_Index1();
	void testAGN934XNI_ATTR_VIDEO_BANDWIDTH_RandomValue_ReadWrite_NullChannel_Index1();
	void testAGN934XNI_ATTR_VIDEO_BANDWIDTH_ViolationMinValue_ReadWrite_NullChannel_Index1();
	void testAGN934XNI_ATTR_VIDEO_BANDWIDTH_ViolationMaxValue_ReadWrite_NullChannel_Index1();

	void testAGN934XNI_ATTR_VIDEO_BANDWIDTH_AUTO_defaultValue_ReadWrite_NullChannel_Index0();
};